# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="dallas"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git bundler dotenv macos fasd zsh-autosuggestions asdf lpass)

source $ZSH/oh-my-zsh.sh

# Enable individual tab history
setopt inc_append_history
unsetopt share_history

# User configuration

#Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Adding go to the path
export PATH=$PATH:/usr/local/go/bin

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# EXPORTS
# You may need to manually set your language environment
export LANG=en_US.UTF-8

# asdf
export ASDF_COMPLETIONS=/Users/khamidi/.asdf/completions
export ASDF_DIR=/Users/khamidi/.asdf

# Dallas
export DALLAS_CURRENT_LOCA_=$'%{\C-[[36m%}%~$(parse_git_dirty)$(git_prompt_info)%{\C-[[00m%}'
export DALLAS_CURRENT_MACH_=$'%{%{\C-[[38;5;008m%}%}%m%{\C-[[37m%}:%{\C-[[00m%}'
export DALLAS_CURRENT_TIME_=$'%{%}$(date +%T) %{\C-[[00m%}'
export DALLAS_CURRENT_USER_=$'%{%{\C-[[38;5;093m%}%}%n%{\C-[[00m%}'
export DALLAS_PROMPT_CHAR_=$'%{\C-[[37m%}%(!.#.%%)%{\C-[[00m%}'

# Homebrew
export HOMEBREW_CELLAR=/opt/homebrew/Cellar
export HOMEBREW_PREFIX=/opt/homebrew
export HOMEBREW_REPOSITORY=/opt/homebrew

# needed for mysql
export LDFLAGS=-L/usr/local/opt/openssl/lib

# java home
export JAVA_HOME=$(/usr/libexec/java_home)

# golang stuff
export GOPRIVATE=""
export GOPATH="${HOME}/go"
export GO111MODULE="on"
export PATH="${PATH}:${GOPATH}/bin"
export VAULT_ADDR=""
export RC_HOSTNAME="$(hostname)"

# python stuff
export PIPENV_IGNORE_VIRTUALENVS=1
export PIPENV_VENV_IN_PROJECT=1
export VIRTUALENV_PIP=23.2.1
export PYPI_FLAG='--pypi-mirror ""'

# ALIASES
# show zsh colors
alias zsh_colors_list="spectrum_ls"

# ipython in virualenv
alias ipy="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"

#alias tmux="tmux -S"
#
## mysql 8.0
export PATH="/opt/homebrew/opt/mysql@8.0/bin/:$PATH"

# docker-compose
alias docker-compose="docker compose"

# This is needed for kafka
export C_INCLUDE_PATH="/opt/homebrew/Cellar/librdkafka/2.10.0/include"

# Cmake:
export PATH=$PATH:/Applications/CMake.app/Contents/bin

# android stuff:
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# git
alias gitlog='git --no-pager log --graph --decorate -n 10 --pretty=format:"%C(yellow)%h%Creset - %Cgreen%ad%Creset %C(auto)%d%Creset %C(blue)<%an>%Creset %s" --date=short'

TMUX_TMPDIR='/tmp/tmux/'
